"""create (GamesRPG, GamesStrategy, GamesSimulation)

Revision ID: 00cf61749612
Revises: f7c0e2cd466b
Create Date: 2026-01-06 19:40:29.265955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cf61749612'
down_revision: Union[str, Sequence[str], None] = 'f7c0e2cd466b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamesrpg',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('gameplay', sa.Text(), nullable=False),
    sa.Column('graphics', sa.Text(), nullable=True),
    sa.Column('game_development', sa.Text(), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamessimulation',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('gameplay', sa.Text(), nullable=False),
    sa.Column('graphics', sa.Text(), nullable=True),
    sa.Column('game_development', sa.Text(), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamesstrategy',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('gameplay', sa.Text(), nullable=False),
    sa.Column('graphics', sa.Text(), nullable=True),
    sa.Column('game_development', sa.Text(), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamesstrategy')
    op.drop_table('gamessimulation')
    op.drop_table('gamesrpg')
    # ### end Alembic commands ###
