"""update User

Revision ID: 012adfb8d01a
Revises: 576d8cc115dd
Create Date: 2026-01-06 18:38:53.642499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012adfb8d01a'
down_revision: Union[str, Sequence[str], None] = '576d8cc115dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('date_registration', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('cookie', sa.String(), nullable=False))
    op.add_column('users', sa.Column('access_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'cookie')
    op.drop_column('users', 'date_registration')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
