"""change fkey on table games

Revision ID: 183285722870
Revises: 70df96652da5
Create Date: 2026-02-22 14:32:58.384969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "183285722870"
down_revision: Union[str, Sequence[str], None] = "70df96652da5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesuserratings", sa.Column("game_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(
        op.f("gamesuserratings_game_fkey"), "gamesuserratings", type_="foreignkey"
    )
    op.create_foreign_key(
        "ratings_fkey",
        "gamesuserratings",
        "games",
        ["game_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("gamesuserratings", "game")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesuserratings",
        sa.Column("game", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("ratings_fkey", "gamesuserratings", type_="foreignkey")
    op.create_foreign_key(
        op.f("gamesuserratings_game_fkey"),
        "gamesuserratings",
        "games",
        ["game"],
        ["name"],
        ondelete="CASCADE",
    )
    op.drop_column("gamesuserratings", "game_id")
    # ### end Alembic commands ###
