"""Create privilege fields to Users

Revision ID: 1f81fa1e395c
Revises: 306a5e8f921f
Create Date: 2026-01-27 19:02:29.535883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f81fa1e395c'
down_revision: Union[str, Sequence[str], None] = '306a5e8f921f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privilege_level', sa.Enum('weak', 'medium', 'best', name='privilege_level'), nullable=True))
    op.add_column('users', sa.Column('cookie_privileged', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('cookie_privileged_expires', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cookie_privileged_expires')
    op.drop_column('users', 'cookie_privileged')
    op.drop_column('users', 'privilege_level')
    # ### end Alembic commands ###
