"""update websocketconnections - add connection_type for detection operators/clients

Revision ID: 306a5e8f921f
Revises: a66f89ba4d85
Create Date: 2026-01-25 14:31:57.335693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306a5e8f921f'
down_revision: Union[str, Sequence[str], None] = 'a66f89ba4d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('websocketconnections', sa.Column('connection_type', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('websocketconnections', 'connection_type')
    # ### end Alembic commands ###
