"""add frontend_db column release_year

Revision ID: 38eeff812712
Revises: b7d1f3ebc595
Create Date: 2026-01-08 15:11:38.749987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38eeff812712"
down_revision: Union[str, Sequence[str], None] = "b7d1f3ebc595"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("release_year", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "release_year")
    # ### end Alembic commands ###
