"""add favorite_genre to display pages individually for a specific user

Revision ID: 4460d6cb924e
Revises: ae7d72507712
Create Date: 2026-01-21 16:52:47.354817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4460d6cb924e'
down_revision: Union[str, Sequence[str], None] = 'ae7d72507712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_genre', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_genre')
    # ### end Alembic commands ###
