"""add foreignkey users-websocketconnections

Revision ID: 59d6783d80f7
Revises: 1f81fa1e395c
Create Date: 2026-02-01 19:16:30.236674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59d6783d80f7"
down_revision: Union[str, Sequence[str], None] = "1f81fa1e395c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "websocketconnections", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "websocketconnections",
        "connected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_foreign_key(
        "websocketconnections_fkey",
        "websocketconnections",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "websocketconnections_fkey", "websocketconnections", type_="foreignkey"
    )
    op.alter_column(
        "websocketconnections",
        "connected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("websocketconnections", "user_id")
    # ### end Alembic commands ###
