"""change GamesUserLiked and Users - add on delete cascade, relationships so that when logging out, the user is deleted from both tables

Revision ID: 68e270995e56
Revises: 54064b5cb7f5
Create Date: 2026-01-09 16:00:27.602627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e270995e56'
down_revision: Union[str, Sequence[str], None] = '54064b5cb7f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('gamesuserliked_user_id_fkey'), 'gamesuserliked', type_='foreignkey')
    op.create_foreign_key(None, 'gamesuserliked', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gamesuserliked', type_='foreignkey')
    op.create_foreign_key(op.f('gamesuserliked_user_id_fkey'), 'gamesuserliked', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
