"""created a field for tracking the binding of the payment method

Revision ID: 70df96652da5
Revises: 2f76b9a8089d
Create Date: 2026-02-19 18:12:36.920103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70df96652da5'
down_revision: Union[str, Sequence[str], None] = '2f76b9a8089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_for_linking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_for_linking')
    # ### end Alembic commands ###
