"""deleted genres tables

Revision ID: 7a533be31c27
Revises: 7ccb9764174d
Create Date: 2026-01-06 20:41:25.595852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a533be31c27"
down_revision: Union[str, Sequence[str], None] = "7ccb9764174d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gamesadventure")
    op.drop_table("gamesrpg")
    op.drop_table("gamesstrategy")
    op.drop_table("gamessimulation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
