"""add fkey

Revision ID: 7afc03a638cc
Revises: bbd803281a20
Create Date: 2026-01-11 13:41:44.686643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7afc03a638cc"
down_revision: Union[str, Sequence[str], None] = "bbd803281a20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gamesuserliked",
        "game",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None, "gamesuserliked", "games", ["game"], ["name"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "gamesuserliked", type_="foreignkey")
    op.alter_column(
        "gamesuserliked",
        "game",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
