"""remove genres tables, created genre enum

Revision ID: 7ccb9764174d
Revises: 00cf61749612
Create Date: 2026-01-06 20:35:52.254110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ccb9764174d"
down_revision: Union[str, Sequence[str], None] = "00cf61749612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "genre",
            sa.Enum(
                "ACTION", "ADVENTURE", "RPG", "STRATEGY", "SIMULATION", name="gamegenre"
            ),
            nullable=False,
        ),
        sa.Column("story", sa.Text(), nullable=False),
        sa.Column("gameplay", sa.Text(), nullable=False),
        sa.Column("graphics", sa.Text(), nullable=True),
        sa.Column("game_development", sa.Text(), nullable=True),
        sa.Column("gallery", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("gamesaction")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gamesaction",
        sa.Column(
            "id",
            sa.BIGINT(),
            sa.Identity(
                always=True,
                start=1,
                increment=1,
                minvalue=1,
                maxvalue=9223372036854775807,
                cycle=False,
                cache=1,
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("story", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("gameplay", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("graphics", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("game_development", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("gallery", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("gamesaction_pkey")),
    )
    op.drop_table("games")
    # ### end Alembic commands ###
