"""Added relationships Users/Games Rating to update the data in the tables when deleting an account

Revision ID: ae7d72507712
Revises: 2c681c2c08fe
Create Date: 2026-01-19 19:39:55.702457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7d72507712'
down_revision: Union[str, Sequence[str], None] = '2c681c2c08fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
