"""add field is_superuser Users table

Revision ID: aed9e5a5f399
Revises: 7afc03a638cc
Create Date: 2026-01-13 20:02:47.019900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aed9e5a5f399"
down_revision: Union[str, Sequence[str], None] = "7afc03a638cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_superuser", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_superuser")
    # ### end Alembic commands ###
