"""change frontend_db field cookie

Revision ID: be8cce6fd1e8
Revises: 0634358cea97
Create Date: 2026-01-07 14:44:09.544631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be8cce6fd1e8"
down_revision: Union[str, Sequence[str], None] = "0634358cea97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "cookie", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "cookie", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
