"""change fkey on table gamesliked

Revision ID: d4a46cebf101
Revises: 183285722870
Create Date: 2026-02-22 14:59:20.826060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4a46cebf101"
down_revision: Union[str, Sequence[str], None] = "183285722870"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesuserliked", sa.Column("game_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(
        op.f("gamesuserliked_game_fkey"), "gamesuserliked", type_="foreignkey"
    )
    op.create_foreign_key(
        "liked_games_fkey",
        "gamesuserliked",
        "games",
        ["game_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("gamesuserliked", "game")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamesuserliked",
        sa.Column("game", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("liked_games_fkey", "gamesuserliked", type_="foreignkey")
    op.create_foreign_key(
        op.f("gamesuserliked_game_fkey"),
        "gamesuserliked",
        "games",
        ["game"],
        ["name"],
        ondelete="CASCADE",
    )
    op.drop_column("gamesuserliked", "game_id")
    # ### end Alembic commands ###
