"""add fkey game->gamescharacteristics

Revision ID: d818679514d8
Revises: 4460d6cb924e
Create Date: 2026-01-23 18:30:08.413580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d818679514d8"
down_revision: Union[str, Sequence[str], None] = "4460d6cb924e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamescharacteristics", sa.Column("game_id", sa.BigInteger(), nullable=False)
    )
    op.drop_constraint(
        op.f("gamescharacteristics_game_name_fkey"),
        "gamescharacteristics",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_gamescharacteristics_game_id",
        "gamescharacteristics",
        "games",
        ["game_id"],
        ["id"],
    )
    op.drop_column("gamescharacteristics", "game_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gamescharacteristics",
        sa.Column("game_name", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        "fk_gamescharacteristics_game_id", "gamescharacteristics", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("gamescharacteristics_game_name_fkey"),
        "gamescharacteristics",
        "games",
        ["game_name"],
        ["name"],
    )
    op.drop_column("gamescharacteristics", "game_id")
    # ### end Alembic commands ###
