"""add GamesCharacteristics

Revision ID: f1ee921362c3
Revises: 7a533be31c27
Create Date: 2026-01-06 21:08:44.612985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1ee921362c3"
down_revision: Union[str, Sequence[str], None] = "7a533be31c27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_games_name", "games", ["name"])
    op.create_table(
        "gamescharacteristics",
        sa.Column("game_name", sa.Text(), nullable=False),
        sa.Column("oc", sa.Text(), nullable=False),
        sa.Column("cpu", sa.Text(), nullable=False),
        sa.Column("gpu", sa.Text(), nullable=False),
        sa.Column("ram", sa.Text(), nullable=False),
        sa.Column("disk_space", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_name"],
            ["games.name"],
        ),
        sa.PrimaryKeyConstraint("game_name"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_games_name", "games", type_="unique")
    op.drop_table("gamescharacteristics")
    # ### end Alembic commands ###
