"""create (GamesAdventure, GamesAction)

Revision ID: f7c0e2cd466b
Revises: 889e5b768820
Create Date: 2026-01-06 19:33:45.197705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c0e2cd466b'
down_revision: Union[str, Sequence[str], None] = '889e5b768820'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamesaction',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('gameplay', sa.Text(), nullable=False),
    sa.Column('graphics', sa.Text(), nullable=True),
    sa.Column('game_development', sa.Text(), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamesadventure',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('gameplay', sa.Text(), nullable=False),
    sa.Column('graphics', sa.Text(), nullable=True),
    sa.Column('game_development', sa.Text(), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gamesadventure')
    op.drop_table('gamesaction')
    # ### end Alembic commands ###
